version: 2.1
orbs:
  node: circleci/node@2.0.2
  kubernetes: circleci/kubernetes@0.11.0
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-eks: circleci/aws-eks@0.2.7
  aws-cli: circleci/aws-cli@0.1.4

defaults: &defaults
  docker:
    - image: circleci/node:13.13.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn cache
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install modules
          command: yarn --frozen-lockfile install
      - save_cache:
          name: Save yarn cache
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Building services
          command: yarn build
          no_output_timeout: 30m
      - persist_to_workspace:
          root: ./
          paths:
            - build
            - src
            - public
            - devops
            - .git
            - node_modules
            - codecov.yml
            - yarn.lock
            - package.json
            - jest.json
            - tsconfig.json
            - Dockerfile

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          name: Restore yarn cache
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Running tests
          # command: yarn test
          command: echo "No tests yet"
      - save_cache:
          name: Save yarn cache
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      # - persist_to_workspace:
      #     root: ./
      #     paths:
      #       - coverage

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          name: Restore yarn cache
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Running lint
          # command: yarn lint
          command: echo "No linting yet"
      - restore_cache:
          name: Restore yarn cache
          key: node-modules-{{ checksum "yarn.lock" }}

  codecov:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          name: Restore yarn cache
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Running code coverage
          command: echo "No codecov yet"
      - restore_cache:
          name: Restore yarn cache
          key: node-modules-{{ checksum "yarn.lock" }}

  push-image:
    <<: *defaults
    parameters:
      deployment-name:
        description: |
          Name of the deployment
        type: string
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Prepare directory
          command: |
            ls .
            TAG=`echo $CIRCLE_BRANCH | sed 's/\\//_/g'`
            echo "TAG is $TAG"
            echo "export TAG=$TAG" >> $BASH_ENV
      # These envvars are set in CircleCI
      - aws-ecr/build-and-push-image:
          setup-remote-docker: true
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          create-repo: true
          checkout: false
          repo: vcexplorerdemo
          tag: "$TAG,$TAG-$CIRCLE_SHA1"

  deploy-image:
    <<: *defaults
    parameters:
      deployment-name:
        description: |
          Name of the deployment
        type: string
      cluster-name:
        description: |
          Name of the cluster
        type: string
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Set up tag var
          command: |
            TAG=`echo $CIRCLE_BRANCH | sed 's/\\//_/g'`
            echo "TAG is $TAG"
            echo "export TAG=$TAG" >> $BASH_ENV
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-region: $AWS_REGION
      - aws-eks/update-kubeconfig-with-authenticator:
          aws-region: $AWS_REGION
          install-kubectl: true
          verbose: true
          cluster-name: << parameters.cluster-name >>
      - deploy:
          name: Update Kubernetes Deployment
          command: |
            TAG=`echo $CIRCLE_BRANCH | sed 's/\\//_/g'`
            kubectl set image deployment/<< parameters.deployment-name >> << parameters.deployment-name >>=$AWS_ECR_ACCOUNT_URL/vcexplorerdemo:$TAG-$CIRCLE_SHA1

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - codecov:
          requires:
            - test
      - push-image:
          name: push-ui-image
          deployment-name: ui
          requires:
            - build
            - test
            - lint
            - codecov
          filters:
            branches:
              only:
                - master
                - sruddy/continuous-deploy
      - deploy-image:
          name: deploy-ui-image
          deployment-name: ui
          cluster-name: alpha
          requires:
            - push-ui-image
          filters:
            branches:
              only:
                - master
                - sruddy/continuous-deploy
